-- local v1
-- local v2 = 1
-- local v3,v4
-- local v1,v5 = 2
-- print("hello world", v1, 1)
-- obj:print(1 + 2, true, a.b)
-- a.b = 1 + 2 - 3
-- local function f1(b, c)
	a = 1
-- end
-- function f2(a,b)
-- end
-- return v2