// Code generated by protoc-gen-go.
// source: projects/bma.go.esp/src/testapp/cluster/interfaces/account.proto
// DO NOT EDIT!

package interfaces

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Req4AccountGet struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req4AccountGet) Reset()         { *m = Req4AccountGet{} }
func (m *Req4AccountGet) String() string { return proto.CompactTextString(m) }
func (*Req4AccountGet) ProtoMessage()    {}

func (m *Req4AccountGet) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Resp4AccountGet struct {
	Result           *int64 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp4AccountGet) Reset()         { *m = Resp4AccountGet{} }
func (m *Resp4AccountGet) String() string { return proto.CompactTextString(m) }
func (*Resp4AccountGet) ProtoMessage()    {}

func (m *Resp4AccountGet) GetResult() int64 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type Req4AccountModify struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *int64  `protobuf:"varint,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req4AccountModify) Reset()         { *m = Req4AccountModify{} }
func (m *Req4AccountModify) String() string { return proto.CompactTextString(m) }
func (*Req4AccountModify) ProtoMessage()    {}

func (m *Req4AccountModify) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Req4AccountModify) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Resp4AccountModify struct {
	Result           *int64 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp4AccountModify) Reset()         { *m = Resp4AccountModify{} }
func (m *Resp4AccountModify) String() string { return proto.CompactTextString(m) }
func (*Resp4AccountModify) ProtoMessage()    {}

func (m *Resp4AccountModify) GetResult() int64 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
}
