package lua51

const (
	LUA_MULTRET = -1

	LUA_REGISTRYINDEX = -10000
	LUA_ENVIRONINDEX  = -10001
	LUA_GLOBALSINDEX  = -10002

	LUA_YIELD     = 1
	LUA_ERRRUN    = 2
	LUA_ERRSYNTAX = 3
	LUA_ERRMEM    = 4
	LUA_ERRERR    = 5
	LUA_ERRFILE   = (LUA_ERRERR + 1)

	LUA_TNONE          = -1
	LUA_TNIL           = 0
	LUA_TBOOLEAN       = 1
	LUA_TLIGHTUSERDATA = 2
	LUA_TNUMBER        = 3
	LUA_TSTRING        = 4
	LUA_TTABLE         = 5
	LUA_TFUNCTION      = 6
	LUA_TUSERDATA      = 7
	LUA_TTHREAD        = 8

	LUA_GCSTOP       = 0
	LUA_GCRESTART    = 1
	LUA_GCCOLLECT    = 2
	LUA_GCCOUNT      = 3
	LUA_GCCOUNTB     = 4
	LUA_GCSTEP       = 5
	LUA_GCSETPAUSE   = 6
	LUA_GCSETSTEPMUL = 7

	LUA_HOOKCALL    = 0
	LUA_HOOKRET     = 1
	LUA_HOOKLINE    = 2
	LUA_HOOKCOUNT   = 3
	LUA_HOOKTAILRET = 4

	LUA_MASKCALL  = (1 << LUA_HOOKCALL)
	LUA_MASKRET   = (1 << LUA_HOOKRET)
	LUA_MASKLINE  = (1 << LUA_HOOKLINE)
	LUA_MASKCOUNT = (1 << LUA_HOOKCOUNT)

	LUA_NOREF  = (-2)
	LUA_REFNIL = (-1)
)
